manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # support nice_oled and nice_epaper (Zephyr 4.1 + LVGL 9 compatible)
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper (Zephyr 4.1 + LVGL 9 compatible)
    - name: zmk-nice-oled
      remote: tokyo2006
      revision: 4.0
  self:
    path: config