---
include:
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_epaper
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: corne_right nice_view_adapter nice_epaper
  - board: nice_nano//zmk
    shield: settings_reset
