# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'firmware/config/*.keymap'
      - 'firmware/config/includes/*.dtsi'
      - 'firmware/keymap-drawer/config.yaml'
      - '.github/workflows/draw-keymaps.yml'

permissions:
  contents: write

concurrency:
  group: keymap-drawer
  cancel-in-progress: true

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@e30a2e6ae744fa23b943938f3c8ba7b6c675e38e
    with:
      keymap_patterns: 'firmware/config/*.keymap'
      config_path: firmware/keymap-drawer/config.yaml
      output_folder: firmware/keymap-drawer
      install_branch: v0.20.0
      amend_commit: false
      fail_on_error: true
